// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: idCards", Justification = "<Pending>", Scope = "member", Target = "~F:CapsSorter.idCards")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: idCardsNotPlayed", Justification = "<Pending>", Scope = "member", Target = "~F:CapsSorter.idCardsNotPlayed")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: iDCardsPlayed", Justification = "<Pending>", Scope = "member", Target = "~F:CapsSorter.iDCardsPlayed")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: currentDifficulty", Justification = "<Pending>", Scope = "member", Target = "~F:IDCard.currentDifficulty")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: idWeight", Justification = "<Pending>", Scope = "member", Target = "~F:IDCard.idWeight")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: inputs", Justification = "<Pending>", Scope = "member", Target = "~F:IDCard.inputs")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: microGameScene", Justification = "<Pending>", Scope = "member", Target = "~F:IDCard.microGameScene")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: trio", Justification = "<Pending>", Scope = "member", Target = "~F:IDCard.trio")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: gameRewards", Justification = "<Pending>", Scope = "member", Target = "~F:Islands.IslandCreator.gameRewards")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: soundBpms", Justification = "<Pending>", Scope = "member", Target = "~F:SoundList.soundBpms")]
[assembly: SuppressMessage("Build", "UNT0013:SerializeField attribute is invalid or redundant for property or field: soundClassic", Justification = "<Pending>", Scope = "member", Target = "~F:SoundList.soundClassic")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:ACommeAkuma.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:ACommeAkuma.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0002:Comparing tags using == is inefficient.", Justification = "<Pending>", Scope = "member", Target = "~M:ACommeAkuma.SaveThePirate.PlayerController.OnCollisionEnter2D(UnityEngine.Collision2D)")]
[assembly: SuppressMessage("Build", "UNT0002:Comparing tags using == is inefficient.", Justification = "<Pending>", Scope = "member", Target = "~M:ACommeAkuma.SaveThePirate.PlayerController.OnTriggerEnter2D(UnityEngine.Collider2D)")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Boss.BossLifeManager.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Brigantin.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Brigantin.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:DragonPepere.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:DragonPepere.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Fleebos.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Fleebos.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:LeRafiot.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:LeRafiot.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:LLL.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:LLL.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:MenuManager.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Player.PlayerInventory.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Player.PlayerInventory.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Player.TempIslands.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Player.TempIslands.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:RadioRTL.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:RadioRTL.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:SAS.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:SAS.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Soupe.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:Soupe.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:SpanishInquisition.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:SpanishInquisition.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Start\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:TrapioWare.MiniGame1.EmptyScript.Start")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:TrapioWare.MiniGame1.EmptyScript.Update")]
[assembly: SuppressMessage("Build", "UNT0001:The Unity message \"Update\" is empty.", Justification = "<Pending>", Scope = "member", Target = "~M:UI.PlayerRessourcesUI.Update")]
